### ISSUE TITLE
Resolve a Python Traceback

### ISSUE THREAD

**Issue by keivalya** [keivalya/dungeon#18]
My inputs: 
Name, age, yes,
left > around > house

```
Traceback (most recent call last):
  File "dungeon.py", line 22, in <module>
    ObjFlow.main()
  File "dungeon.py", line 16, in main
    game.wantsToPlay(0)
  File "C:\...\dungeon-master\dungeon-master\Game.py", line 44, in wantsToPlay
    health -= 10
UnboundLocalError: local variable 'health' referenced before assignment
```

Go through the README.md, you'll come to know how this game works, and then resolving this issue would become very easy.
Mention the issue # if you create a PR

**Comment by ravish0007** [comment]
on it
